### ISSUE TITLE
register crushes

### ISSUE THREAD

**Issue by najm07** [shem8/MaterialLogin#36]
whenever i click the + button it fore close

**Comment by shem8** [comment]
Can you please elaborate a little more?
What's the error?

**Comment by najm07** [comment]
when i want to change to register view the app crushes and force colsing

**Comment by shem8** [comment]
Can you put here the full stack trace?

**Comment by najm07** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.drinfo.tklm, PID: 1952
                  java.lang.NoSuchMethodError: io.codetail.animation.ViewAnimationUtils.createCircularReveal
                      at shem.com.materiallogin.MaterialLoginView.getCircularRevealAnimation(MaterialLoginView.java:189)
                      at shem.com.materiallogin.MaterialLoginView.access$400(MaterialLoginView.java:40)
                      at shem.com.materiallogin.MaterialLoginView$3.onAnimationStart(MaterialLoginView.java:156)
                      at android.view.animation.Animation$1.run(Animation.java:360)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5017)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by shem8** [comment]
Make sure you added the (CircularReveal)[https://github.com/ozodrukh/CircularReveal] lib

**Comment by shem8** [comment]
Should be ok now
