### ISSUE TITLE
Cannot register twice successively

### ISSUE THREAD

**Issue by elhexx** [shem8/MaterialLogin#41]
i got this message error when i try to register twice successively :

`java.lang.NullPointerException: Attempt to invoke interface method 'void shem.com.materiallogin.DefaultRegisterView$DefaultRegisterViewListener.onRegister(android.support.design.widget.TextInputLayout, android.support.design.widget.TextInputLayout, android.support.design.widget.TextInputLayout)' on a null object reference
        at shem.com.materiallogin.DefaultRegisterView$1.onClick(DefaultRegisterView.java:67)
        at android.view.View.performClick(View.java:4780)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

**Comment by shem8** [comment]
WDYM by twice? like clicking twice?

**Comment by elhexx** [comment]
if i submit registration for user1, and when i try to submit new registration for user2, the previous error will occured.

**Comment by shem8** [comment]
ohh gotcha.
Can you please attach some sample code for 2 regiatrations so it'll be
easier to reproduce and debug?

**Comment by elhexx** [comment]
Also if i registred a new user, the login button doesn't work like if it is disabled, so i must restart the application the login.

```JAVA
final MaterialLoginView login = (MaterialLoginView) findViewById(R.id.login);

        ((DefaultLoginView)login.getLoginView()).setListener(new DefaultLoginView.DefaultLoginViewListener() {
            @Override
            public void onLogin(TextInputLayout loginUser, TextInputLayout loginPass) {
                //Handle login
                login(loginUser.getEditText().getText().toString(), loginPass.getEditText().getText().toString());
            }
        });

((DefaultRegisterView)login.getRegisterView()).setListener(new DefaultRegisterView.DefaultRegisterViewListener() {
            @Override
            public void onRegister(TextInputLayout registerUser, TextInputLayout registerPass, TextInputLayout registerPassRep) {
                //Handle register
                register(registerUser.getEditText().getText().toString(),
                        registerPass.getEditText().getText().toString(),
                        registerPassRep.getEditText().getText().toString());

            }
        });
```
