### ISSUE TITLE
Register Button Not working

### ISSUE THREAD

**Issue by JAICHANGPARK** [shem8/MaterialLogin#43]
I added 

```
dependencies {
	    implementation ('com.github.ozodrukh:CircularReveal:2.0.1@aar') {
	        transitive = true;
	    }
	}
```
and when I Clicked Register Button 
App was crashed 
```

java.lang.NoSuchMethodError: No static method createCircularReveal(Landroid/view/View;IIFF)Lio/codetail/animation/SupportAnimator; in class Lio/codetail/animation/ViewAnimationUtils; or its super classes (declaration of 'io.codetail.animation.ViewAnimationUtils' appears in /data/app/com.dreamwalker.diabetesfits-1/split_lib_dependencies_apk.apk)
        at shem.com.materiallogin.MaterialLoginView.getCircularRevealAnimation(MaterialLoginView.java:189)
        at shem.com.materiallogin.MaterialLoginView.access$400(MaterialLoginView.java:40)
        at shem.com.materiallogin.MaterialLoginView$3.onAnimationStart(MaterialLoginView.java:156)
        at android.view.animation.Animation$1.run(Animation.java:367)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

```

**Comment by shem8** [comment]
Are you sure you're using the latest version (2.1.0)?
